opt_in_rules:
    - empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    
# rule specific config
trailing_comma:
  mandatory_comma: true
identifier_name:
  min_length:   # only min_length
    error: 3    # only error
  excluded:     # excluded via string array
    - id
    - URL

line_length:
  - 300 # warning
  - 400 # error

function_body_length:
  - 300 # warning
  - 400 # error

type_body_length:
  - 300 # warning
  - 400 # error
